"""empty message

Revision ID: 2dbf5fb58ddd
Revises: 
Create Date: 2024-12-05 07:00:59.802332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbf5fb58ddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtm_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mtm_child_col', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='python_test_deploy_schema'
    )
    op.create_table('mtm_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mtm_parent_col', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='python_test_deploy_schema'
    )
    op.create_table('parent_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_a', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='python_test_deploy_schema'
    )
    op.create_table('parent_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_b', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='python_test_deploy_schema'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='python_test_deploy_schema'
    )
    op.create_table('child_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_a', sa.String(length=100), nullable=False),
    sa.Column('parent_a_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_a_id'], ['python_test_deploy_schema.parent_a.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='python_test_deploy_schema'
    )
    op.create_table('child_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_b', sa.String(length=100), nullable=False),
    sa.Column('parent_b_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_b_id'], ['python_test_deploy_schema.parent_b.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='python_test_deploy_schema'
    )
    op.create_table('mtm_parent_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mtm_extra_data', sa.String(length=150), nullable=False),
    sa.Column('mtm_parent_join_id', sa.Integer(), nullable=True),
    sa.Column('mtm_child_join_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mtm_child_join_id'], ['python_test_deploy_schema.mtm_children.id'], ),
    sa.ForeignKeyConstraint(['mtm_parent_join_id'], ['python_test_deploy_schema.mtm_parents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='python_test_deploy_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mtm_parent_children', schema='python_test_deploy_schema')
    op.drop_table('child_b', schema='python_test_deploy_schema')
    op.drop_table('child_a', schema='python_test_deploy_schema')
    op.drop_table('users', schema='python_test_deploy_schema')
    op.drop_table('parent_b', schema='python_test_deploy_schema')
    op.drop_table('parent_a', schema='python_test_deploy_schema')
    op.drop_table('mtm_parents', schema='python_test_deploy_schema')
    op.drop_table('mtm_children', schema='python_test_deploy_schema')
    # ### end Alembic commands ###
